apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fossflow-postgres
  namespace: fossflow
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: "15.5.18"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      database: fossflow
      username: fossflow
      existingSecret: "fossflow-postgres-creds"
    primary:
      persistence:
        enabled: true
        storageClass: "local-path"
        size: 5Gi