# adguard-home.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: oci://ghcr.io/gabe565/charts/adguard-home
      version: "0.13.0" #última versión estable de este chart
      sourceRef:

        kind: OCIRepository
        name: adguard-home-oci # 
        namespace: flux-system # OCIRepository también viven en flux-system
  values:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 4Gi
    ingress:
      enabled: true
      # explícitamente a Traefik que use este Ingress
      className: traefik
      hosts:
        - host: adguard.homelab.local
          paths:
            - path: /
              pathType: Prefix
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: adguard-home-oci
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/gabe565/charts
  ref:
    tag: "adguard-home-0.13.0"