apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
# PASO 1: Definir la fuente OCI
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: adguard-home-source
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/gabe565/charts
  ref:
    semver: ">=0.1.0"
---
# PASO 2: Crear una plantilla de HelmChart a partir de la fuente
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: adguard-home-chart-template
  namespace: flux-system
spec:
  interval: 1h
  chart: adguard-home
  version: "0.13.0"
  sourceRef:
    kind: OCIRepository
    name: adguard-home-source # Apunta a la fuente OCI
    namespace: flux-system
---
# PASO 3: Instalar la aplicación usando la plantilla HelmChart
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: adguard-home-chart-template # Apunta a la plantilla, no a la fuente OCI
      version: "0.13.0"
      sourceRef:
        kind: HelmChart # El kind aquí debe ser HelmChart
        name: adguard-home-chart-template
        namespace: flux-system
      reconcileStrategy: ChartVersion
  values:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 4Gi
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: adguard.homelab.local
          paths:
            - path: /
              pathType: Prefix