apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: adguard-home
      version: "2.5.0"
      sourceRef:
        kind: HelmRepository
        # Asegúrate de que apunte al nombre correcto que definimos en sources
        name: adguard-home-charts
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 4Gi
    ingress:
      enabled: true
      hosts:
        - host: adguard.homelab.local
          paths:
            - path: /
              pathType: Prefix