apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: adguard-home
      version: "4.7.1" # Una versión estable de este chart
      sourceRef:
        # Le decimos que apunte DIRECTAMENTE al HelmRepository
        kind: HelmRepository
        name: k8s-at-home # El nombre del repo que acabamos de crear
        namespace: flux-system
  values:
    # La estructura de values puede ser diferente entre charts.
    # Esta es la correcta para el chart de k8s-at-home.
    persistence:
      enabled: true
      storageClassName: "local-path"
      size: 4Gi
    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: adguard.homelab.local
            paths:
              - path: /
                pathType: Prefix