apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nlocal-path
  resources:
    requests:
      storage: 1Gi
  volumeName: radarr-config-pv-temporal