apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-dynamic 
  resources:
    requests:
      storage: 1Gi