# cluster/apps/vpn/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wg-easy
  namespace: vpn
spec:
  interval: 15m
  chart:
    spec:
      chart: wg-easy
      version: "5.1.0" # Use a specific version for reproducibility
      sourceRef:
        kind: HelmRepository
        name: wg-easy
        namespace: flux-system
  values:

    host: "vpn.homelab.local"

    service:
      type: LoadBalancer

      loadBalancerIP: 192.168.1.47
      annotations:
        metallb.universe.tf/allow-shared-ip: wg-easy-svc
    
    ports:
      wireguard:
        port: 51820
        protocol: UDP
      web:
        port: 51821
        protocol: TCP

    # -- Ingress configuration for the Web UI
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - host: "wg.homelab.local"
          paths:
            - path: /
              pathType: Prefix

    env:
      WG_ALLOWED_IPS: "192.168.1.0/24"
      
      WG_EASY_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: wg-easy-secret
            key: WG_EASY_PASSWORD

    persistence:
      enabled: true
      storageClassName: "smb-dynamic" 
      accessModes:
        - ReadWriteOnce
      size: 1Gi