apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-chrome
  namespace: selenium
  labels:
    app: selenium-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-chrome
  template:
    metadata:
      labels:
        app: selenium-chrome
    spec:
      containers:
        - name: selenium-chrome
          image: selenium/standalone-chrome:latest
          ports:
            - containerPort: 4444
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"