# cluster/apps/media-stack/lidarr/lidarr-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: media-stack
  labels:
    app: lidarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      initContainers:
        - name: wait-for-smb
          image: busybox:1.36
          command: ['sh', '-c', 'until mountpoint -q /media; do echo "waiting for SMB mount..."; sleep 5; done']
          volumeMounts:
            - name: downloads
              mountPath: /media
      containers:
        - name: lidarr
          image: blampe/lidarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Mexico_City"
          ports:
            - name: http
              containerPort: 8686
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: lidarr
            - name: downloads 
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lidarr-config
        - name: downloads 
          persistentVolumeClaim:
            claimName: media-nfs-pvcy