# cluster/apps/storage/smb-csi-driver/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: smb-csi-driver-release 
  namespace: kube-system 
spec:
  interval: 15m
  chart:
    spec:
      chart: csi-driver-smb
      version: "1.15.0"
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    fullnameOverride: csi-driver-smb 
