apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: media-stack
  labels:
    app: bazarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      initContainers:
        - name: wait-for-smb
          image: busybox:1.36
          command: ['sh', '-c', 'until [ -d "/media" ] && [ "$(ls -A /media)" ]; do echo "waiting for SMB mount to be populated..."; sleep 5; done']          
          volumeMounts:
            - name: downloads
              mountPath: /media
      containers:
        - name: bazarr
          image: lscr.io/linuxserver/bazarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Mexico_City"
          ports:
            - name: http
              containerPort: 6767
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: bazarr-config
        - name: media
          hostPath:
            path: /mnt/windows-media
            type: Directory