---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "59.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  timeout: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    alertmanager:
      enabled: false

    grafana:
      enabled: true
      admin:
        existingSecret: "grafana-admin-secret"

      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.homelab.local

      persistence:
        enabled: true
        storageClassName: "local-path"

      extraEnv:
        - name: GF_DATABASE_TYPE
          value: "postgres"
        - name: GF_DATABASE_HOST
          value: "postgres-service.default.svc.cluster.local:5432"
        - name: GF_DATABASE_NAME
          value: "grafana"
        - name: GF_DATABASE_SSL_MODE
          value: "disable"
        - name: GF_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: grafana-db-credentials
              key: GF_DATABASE_USER
        - name: GF_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-db-credentials
              key: GF_DATABASE_PASSWORD
        - name: GF_SERVER_ROOT_URL
          value: "http://grafana.homelab.local"

    prometheus:
      enabled: true
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "local-path"
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: "10Gi"