# cluster/apps/homepage/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  # Defaults for homepage
  docker.yaml: ""
  custom.js: ""

  kubernetes.yaml: |
    mode: cluster

  settings.yaml: |
    # The 'clean' header style provides a more minimal look.
    headerStyle: clean
    background:
      image: https://images.unsplash.com/photo-1695376425475-1b6b561f8e4e
      blur: xl
      brightness: 90
      opacity: 60
    cardBlur: sm

  bookmarks.yaml: |
    - Homelab:
        - GitHub:
            - abbr: GH
              href: "https://github.com/foalaniz/homelab-k3s"
    - Cloud & Media:
        - Azure Portal:
            - abbr: AZ
              icon: microsoft-azure
              href: "https://portal.azure.com"
        - YouTube:
            - abbr: YT
              icon: youtube
              href: "https://youtube.com"

  services.yaml: |
    - Networking:
        - Traefik:
            href: http://traefik.homelab.local/dashboard/#/
            description: Traefik Dashboard
            icon: traefik
        - AdGuard:
            href: http://adguard.homelab.local
            description: AdGuard Home
            icon: adguard-home
    - Media:
        - qBittorrent:
            href: http://downloads.homelab.local
            description: Torrent Client
            icon: qbittorrent
        - Overseerr:
            href: http://requests.homelab.local
            description: Request Client
            icon: overseerr
        - Sonarr:
            href: http://series.homelab.local
            description: TV Show Management
            icon: sonarr
        - Radarr:
            href: http://movies.homelab.local
            description: Movie Management
            icon: radarr
        - Lidarr:
            href: http://music.homelab.local
            description: Music Management
            icon: lidarr
        - Navidrome: 
            href: http://navidrome.homelab.local
            description: Music Streaming
            icon: navidrome            
        - Prowlarr:
            href: http://prowlarr.homelab.local
            description: Indexer Manager
            icon: prowlarr
    - Productivity & Tools:
        - N8N:
            href: http://n8n.homelab.local 
            description: Workflow Automation
            icon: n8n
        - Karakeep:
            href: http://karakeep.homelab.local
            description: RSS & Readlater
            icon: Karakeep
    - Database:
        - pgAdmin:
            href: http://pgadmin.homelab.local
            description: PostgreSQL Admin
            icon: pgadmin
    - Monitoring:
        - Grafana:
            href: http://grafana.homelab.local
            description: Metrics Dashboard
            icon: grafana
        - Prometheus:
            href: http://prometheus.homelab.local
            description: Metrics Server
            icon: prometheus

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
        nodes:
          show: true
          cpu: true
          memory: true
    - resources:
        cpu: true
        memory: true
    - greeting:
        text_size: xl
        text: Cuervo Homelab       

  custom.css: |
    /* Optional: Adjust text color for better readability on transparent backgrounds */
    body, h1, h2, h3, h4, h5, h6, p, span, a, .text-color {
      color: #f0f0f0; /* Light color for text */
      text-shadow: 1px 1px 2px rgba(0,0,0,0.5); /* Subtle shadow for text readability */
    }

    /* Make sure icons are visible */
    .icon {
      filter: drop-shadow(1px 1px 2px rgba(0,0,0,0.5));
    }