# cluster/apps/homepage/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: media-stack
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      annotations:
        # Forza un reinicio del pod al aplicar este cambio
        restartedAt: "2025-07-17T16:42:00Z"
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          # Se fija una versión específica para mayor estabilidad
          image: "ghcr.io/gethomepage/homepage:v0.9.4"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          # Sondas de salud para que Kubernetes gestione mejor el pod
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: settings
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
            - name: services
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: bookmarks
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: widgets
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
      volumes:
        - name: settings
          configMap:
            name: homepage-settings
        - name: services
          configMap:
            name: homepage-services
        - name: bookmarks
          configMap:
            name: homepage-bookmarks
        - name: widgets
          configMap:
            name: homepage-widgets
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: media-stack
spec:
  selector:
    app: homepage
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000