---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage-deployment
  namespace: default
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.homelab.local,192.168.254.131"
          volumeMounts:
            # El contenedor montará el volumen en su ruta de configuración
            - name: homepage-config-volume
              mountPath: /app/config
      # El volumen se define para que tome su contenido DIRECTAMENTE del ConfigMap
      volumes:
        - name: homepage-config-volume
          configMap:
            name: homepage-config