# cluster/apps/homepage/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: media-stack
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 1.2.0
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v0.9.5

    ingress:
      main:
        enabled: true
        ingressClassName: traefik
        hosts:
          - host: home.homelab.local
            paths:
              - path: /
                pathType: Prefix
        tls: []

    persistence:
      config:
        enabled: true
        type: configMap
        name: homepage-config
        mountPath: /app/config