apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack
data:
  # We only need settings.yaml for the app to start
  settings.yaml: |
    ---
    title: Mi Homelab
    background: "#121212"

  # Leave other files empty for now
  services.yaml: |
    ---
  bookmarks.yaml: |
    ---
  widgets.yaml: |
    ---