apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack 
data:
  # --- Configuración de los servicios que aparecerán en el dashboard ---
  services.yaml: |
    - "Mis Aplicaciones":
        - Sonarr:
            href: http://series.homelab.local
            icon: sonarr.png
            description: Gestor de Series

        - Radarr: # Aunque no esté instalado, lo dejamos de ejemplo
            href: http://movies.homelab.local
            icon: radarr.png
            description: Gestor de Películas

        - Lidarr:
            href: http://music.homelab.local
            icon: lidarr.png
            description: Cliente de Musica

        - Prowlarr:
            href: http://prowlarr.homelab.local
            icon: prowlarrpng
            description: Cliente de TODO

        - qBittorrent:
            href: http://downloads.homelab.local
            icon: qbittorrent.png
            description: Cliente de Descargas



    - "Infraestructura":
        - Traefik:
            href: http://traefik.homelab.local/dashboard/#/
            icon: traefik.png
            description: Dashboard de Traefik

  # --- Configuración de los marcadores ---
  bookmarks.yaml: |
    - Búsqueda:
        - Google:
            href: https://google.com
        - DuckDuckGo:
            href: https://duckduckgo.com


  # --- Configuración de los Widgets ---
  widgets.yaml: |
    - resources:
        label: Cluster
        cpu: true
        memory: true

  # --- Configuración General ---
  settings.yaml: |
    title: Mi Homelab
    background: https://images.unsplash.com/photo-1470813740244-df37b8c1edcb
    # ...puedes añadir más personalización aquí...