apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack
data:
  settings.yaml: |
    ---
    title: Mi Homelab
    background: "#2F4F4F"
  services.yaml: |
    ---
    - "Infraestructura":
        - Traefik:
            href: "http://traefik.homelab.local/dashboard/#/"
            icon: traefik.png