apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  settings.yaml: |
    title: Mi Homelab
    header: Bienvenid@ a mi clúster de k3s
    # Deshabilitar completamente los defaults
    providers:
      kubernetes: false
      docker: false
      bookmarks: false
      services: false
      widgets: false
    background:
      image: https://images.unsplash.com/photo-1506260408121-e353d10b87c7
      blur: sm
      saturate: 50
      brightness: 50
      opacity: 30

  services.yaml: |
    - "Administración del Clúster":
        - "Traefik":
            icon: traefik
            href: "http://192.168.254.131:8080/dashboard/"
            description: "Dashboard del Ingress Controller"
        
        - "Grafana":
            icon: grafana
            href: "http://grafana.homelab.local"
            description: "Dashboards de Monitoreo"

    - "Bases de Datos":
        - "pgAdmin 4":
            icon: postgresql
            href: "http://pgadmin.homelab.local"
            description: "Interfaz para PostgreSQL"

    - "Aplicaciones":
        - "CommaFeed":
            icon: rss
            href: "http://commafeed.homelab.local"
            description: "Lector de feeds RSS"
        
        - "Readeck":
            icon: book-open-page-variant
            href: "http://readeck.homelab.local"
            description: "Lector de artículos guardados"