apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack
data:
  # --- General Settings ---
  settings.yaml: |
    title: Mi Homelab
    background: https://images.unsplash.com/photo-1470813740244-df37b8c1edcb
    search:
      provider: google
      target: _blank

  # --- Services ---
  # Leave this empty for now to fix the error
  services.yaml: |
    - "Mis Aplicaciones":
        - Sonarr:
            href: http://series.homelab.local
            icon: sonarr.png

  # --- Bookmarks ---
  bookmarks.yaml: |
    - Búsqueda:
        - Google:
            href: https://google.com

  # --- Widgets ---
  # Keep your cluster widget
  widgets.yaml: |
    - resources:
        label: Cluster
        cpu: true
        memory: true