apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack 
data:
  bookmarks.yaml: |
    - Búsqueda:
        - Google:
            href: "https://google.com"

  widgets.yaml: |
    - resources:
        label: "Cluster"
        cpu: true
        memory: true

  services.yaml: |
    - "Test Services":
        - Google:
            href: "https://google.com"
            icon: "google.png"
            description: "Test service"

  settings.yaml: |
    title: "Mi Homelab"
    search:
      provider: "google"
      target: "_blank"