# cluster/apps/homepage/homepage-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: media-stack
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          # Use a specific, stable version instead of latest
          image: ghcr.io/gethomepage/homepage:v0.9.5
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "home.homelab.local"
          ports:
            - containerPort: 3000
          # Add these lines to mount the configmap
          volumeMounts:
            - name: config
              mountPath: /app/config
              readOnly: true
      # Add this section to define the volume
      volumes:
        - name: config
          configMap:
            name: homepage-config

---

apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: media-stack
spec:
  selector:
    app: homepage
  ports:
    - port: 3000
      targetPort: 3000

---

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: media-stack
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`home.homelab.local`)
      kind: Rule
      services:
        - name: homepage
          port: 3000