apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack 
data:
  bookmarks.yaml: |
    []

  widgets.yaml: |
    - resources:
        label: "Cluster"
        cpu: true
        memory: true

  services.yaml: |
    - "Test":
        - Google:
            href: "https://google.com"
            description: "Test service"

  settings.yaml: |
    title: "Mi Homelab"