apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack
data:
  # --- General Settings ---
  settings.yaml: |
    title: Mi Homelab
    background: "#2F4F4F" # Dark Slate Gray background

  # --- Services (add your services back here one-by-one) ---
  services.yaml: |
    - "Infrastructure":
        - Traefik:
            href: "http://traefik.homelab.local/dashboard/#/"
            icon: traefik.png

  # --- Bookmarks (can be left empty for now) ---
  bookmarks.yaml: |
    ---

  # --- Widgets (can be left empty for now) ---
  widgets.yaml: |
    ---