apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: media-stack
data:
  # --- General Settings ---
  settings.yaml: |
    title: Mi Homelab
    background: https://images.unsplash.com/photo-1470813740244-df37b8c1edcb
    search:
      provider: google
      target: _blank

  # --- Services ---
  services.yaml: |
    # Dejado en blanco para la prueba

  # --- Bookmarks ---
  bookmarks.yaml: |
    - Búsqueda:
        - Google:
            href: https://google.com
        - DuckDuckGo:
            href: https://duckduckgo.com

  # --- Widgets ---
  widgets.yaml: |
    - resources:
        label: Cluster
        cpu: true
        memory: true