---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  # settings.yaml con lo mínimo indispensable
  settings.yaml: |
    title: Mi Homelab

  # services.yaml con un solo grupo y un solo servicio de prueba
  services.yaml: |
    - "Grupo de Prueba":
        - "Documentación de Homepage":
            icon: book-open-page-variant
            href: "https://gethomepage.dev/"
            description: "Sitio oficial"