apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glance-config
  namespace: glance
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi