apiVersion: v1
kind: Service
metadata:
  name: commafeed
  namespace: media-stack
spec:
  selector:
    app: commafeed
  ports:
    - name: http
      port: 8082
      targetPort: 8082

---

ApiVersion: traefik.io/v1alpha1
kind: IngressRouter
metadata: 
  name: commafeed
  namespace: media-stack
spec:
  entryPoints:
    - web
  router:
    -match: Host(`commafeed.homelab.local`)
    kind: Rule
    services: 
      - name: commafeed
        port: 8082