# cluster/apps/commafeed/commafeed-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
  namespace: media-stack
  labels:
    app: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      containers:
        - name: commafeed
          # --- CHANGE THIS LINE ---
          image: athou/commafeed:5.10.0-postgresql-jvm
          env:
            - name: CF_DATABASE_URL
              value: "jdbc:postgresql://postgresql.database.svc.cluster.local:5432/commafeed"
            - name: CF_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: commafeed-creds
                  key: DB_USER
            - name: CF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commafeed-creds
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080