apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
  namespace: database
  labels:
    app: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      containers:
        - name: commafeed
          image: athou/commafeed:4.5.0
          env:
            - name: COMMAFEED_DATABASE_URL
              value: "postgresql://postgresql.database.svc.cluster.local:5432/commafeed"
            - name: COMMAFEED_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: commafeed-creds
                  key: DB_USER
            - name: COMMAFEED_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commafeed-creds
                  key: DB_PASSWORD
          ports:
            - containerPort: 8080 