apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
  namespace: media-stack
  labels:
    app: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -zv commafeed-db-postgresql.media-stack.svc.cluster.local 5432; do echo "Waiting for database..."; sleep 2; done']
      containers:
        - name: commafeed
          image: athou/commafeed:5.10.0-postgresql-jvm
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: "jdbc:postgresql://commafeed-db-postgresql.media-stack.svc.cluster.local:5432/commafeed"
            - name: QUARKUS_DATASOURCE_USERNAME
              value: "commafeed" 
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commafeed-creds
                  key: DB_PASSWORD
          ports:
            - containerPort: 8082
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "728Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10