apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: commafeed-db
  namespace: media-stack
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: "15.5.18"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      database: commafeed
      username: commafeed
      # Use the standard PostgreSQL secret key names
      existingSecret: "commafeed-creds"
      secretKeys:
        adminPasswordKey: "DB_PASSWORD"
        userPasswordKey: "DB_PASSWORD"
    primary:
      volumePermissions:
        enabled: true
      persistence:
        enabled: true
        storageClass: "smb-strict" 
        subPath: "commafeed-data"        
        size: 2Gi
        subPath: postgresql-data
      # Add initialization script for CommAFeed
      initdb:
        scripts:
          init.sql: |

