apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "28.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    #  servicio sea de tipo LoadBalancer para que MetalLB le dé una IP
    service:
      type: LoadBalancer
      spec: 
      loadBalancerIP: 192.168.1.45
    # Habilita el dashboard de Traefik para poder verlo
    api:
      dashboard: true
      insecure: true #  permite acceder sin HTTPS por ahora

    #  puertos de entrada.
    ports:
      web:
        port: 8000
        # Redirigi el puerto 80 del exterior al puerto 8000 de Traefik
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 8443
        # Redirigis el puerto 443 del exterior al puerto 8443 de Traefik
        exposedPort: 443
        protocol: TCP
      traefik:
        port: 9000