# cluster/apps/traefik-system/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik-system
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: "28.0.0"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.50
    api:
      dashboard: true
      insecure: true
    ports:
      web:
        port: 8000
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 8443
        exposedPort: 443
        protocol: TCP
      traefik:
        port: 9000