---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-monitoring
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/apps/flux-system-monitoring # Apunta a tus archivos de monitoreo de Flux
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn: # <-- ¡Aquí está la magia!
    - name: kube-prometheus-stack  # Espera a que este HelmRelease...
      namespace: monitoring         # ...en este namespace, esté listo.