# cluster/apps/storage/smb-csi-driver/helm-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system 
spec:
  interval: 15m
  chart:
    spec:
      chart: csi-driver-smb
      version: "1.15.0" # Verifica la última versión estable en el repositorio
      sourceRef:
        kind: HelmRepository
        name: csi-driver-smb
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Habilita el provisioner para crear PersistentVolumes dinámicamente
    controller:
      enableProvisioning: true

    # storageClass para el driver SMB
    storageClass:
      enabled: true
      name: smb-client # Nombre de tu nueva StorageClass SMB
      reclaimPolicy: Delete # O Retain
      mountOptions:
        - dir_mode=0777 # Permisos de directorio 
        - file_mode=0777 # Permisos de archivo 
        - vers=3.0 # Versión del protocolo SMB
    