apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/foalaniz/homelab-k3s.git' # Usa la URL de tu repo
    targetRevision: main
    path: cluster/apps/adguard
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true