apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commafeed-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: '15.5.18'
    helm:
      values: |
        auth:
          database: commafeed
          username: commafeed
          existingSecret: "commafeed-creds"
          secretKeys:
            adminPasswordKey: "DB_PASSWORD"
            userPasswordKey: "DB_PASSWORD"
        primary:
          podSecurityContext:
            enabled: true
            fsGroup: 1001
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
          persistence:
            enabled: true
            storageClass: "local-path"  
            size: 2Gi
          initdb:
            scripts:
              init.sql: |
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: media-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true