apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: '15.5.18'
    helm:
      values: |
        auth:
          existingSecret: "postgres-creds"
          database: "homelab"
          secretKeys:
            adminPasswordKey: "postgres-password"
            userPasswordKey: "password"
        primary:
          persistence:
            enabled: true
            storageClass: "local-path"  
            size: 8Gi
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true