# cluster/apps/argo-apps/metallb-install-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-install
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/foalaniz/homelab-k3s.git'
    targetRevision: argo-experiment 
    path: cluster/apps/metallb/install
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true