# cluster/apps/argo-apps/readeck-db-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readeck-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: '15.5.18'
    helm:
      values: |
        auth:
          database: readeck
          username: readeck
        primary:
          podSecurityContext:
            enabled: true
            fsGroup: 1001
          containerSecurityContext:
            enabled: true
            runAsUser: 1001
          persistence:
            enabled: true
            storageClass: "smb-readeck-db"
            size: 5Gi
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: readeck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true