# cluster/apps/argo-apps/readeck-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: readeck
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: 'https://github.com/foalaniz/homelab-k3s.git'
    targetRevision: main
    path: cluster/apps/readeck
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: readeck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true