apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smb-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts'
    chart: csi-driver-smb
    targetRevision: 'v1.9.0'
    helm:
      values: |
        controller:
          replicas: 1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true