apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: '28.0.0'
    helm:
      values: |
        # Enable access logs
        accessLogs:
          enabled: true
        
        # Service configuration
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.1.45
        
        # API and Dashboard configuration
        api:
          dashboard: true
          insecure: true
          debug: true
        
        # Disable the built-in dashboard IngressRoute to avoid conflicts
        ingressRoute:
          dashboard:
            enabled: false
        
        # Port configuration
        ports:
          web:
            port: 8000
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 8443
            exposedPort: 443
            protocol: TCP
          traefik:
            port: 9000
            expose: true
        
        # Additional configuration for debugging
        log:
          level: INFO
        
        # Ensure providers are correctly configured
        providers:
          kubernetesIngress:
            enabled: true
          kubernetesCRD:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true