apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/foalaniz/homelab-k3s.git'
    targetRevision: argo-experiment 
    path: cluster/apps/traefik-system 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true