apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: '28.0.0'
    helm:
      values: |
        # Global configuration
        globalArguments:
          - "--api.insecure=true"
          - "--api.dashboard=true"
          - "--api.debug=true"
        
        # Service configuration
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.100.45
        
        # Ports configuration
        ports:
          web:
            port: 8000
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 8443
            exposedPort: 443
            protocol: TCP
          traefik:
            port: 9000
            exposedPort: 9000
            expose: true
        
        # Deployment configuration
        deployment:
          replicas: 1
        
        # Disable the default ingressroute to avoid conflicts
        ingressRoute:
          dashboard:
            enabled: false
        
        # Additional configuration
        additionalArguments:
          - "--log.level=INFO"
          - "--accesslog=true"
          - "--providers.kubernetesCRD.allowCrossNamespace=true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true