apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-8"
spec:
  project: default
  source:
    repoURL: 'https://helm.traefik.io/traefik'
    chart: traefik
    targetRevision: '28.0.0'
    helm:
      values: |
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.1.45
        
        api:
          dashboard: true
          insecure: true
        
        ingressRoute:
          dashboard:
            enabled: false
        
        ports:
          web:
            port: 8000
            exposedPort: 80
            protocol: TCP
          websecure:
            port: 8443
            exposedPort: 443
            protocol: TCP
          traefik:
            port: 9000
            exposedPort: 9000
            expose: true
        
        entryPoints:
          web:
            address: ":8000"
          websecure:
            address: ":8443"
          traefik:
            address: ":9000"
        
        api:
          dashboard: true
          insecure: true
          debug: true
        
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: traefik-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true