apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 15m
  chart:
    spec:
      chart: metallb
      version: "0.14.7"
      sourceRef:
        kind: HelmRepository
        name: metallb # Usa el repo definido en "sources"
        namespace: flux-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
  labels:
    metallb.io/component: controller
spec:
  addresses:
    # Rango de IPs
    - "192.168.1.44-192.168.1.64"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2-advertisement
  namespace: metallb-system
  labels:
    metallb.io/component: speaker
spec:
  ipAddressPools:
    - main-pool