apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./smb-csi-driver-helm-release.yaml
  - ./smb-storageclass.yaml
  - ./smb-storageclass-strict.yaml
  - ./smb-storageclass-adguard.yaml
  - ./smb-storageclass-postgres.yaml
  - ./smb-storageclass-readeck-db.yaml
