apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-nfs-pv
spec:
  capacity:
    storage: 10Ti 
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" 
  nfs:
    server: 192.168.0.21 
    path: "/mnt/tokyo-3/media"
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - rsize=1048576
    - wsize=1048576