apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-karakeep
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.0.6/k8s-data"
  csi.storage.k8s.io/node-stage-secret-name: "csi-smb-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0666
  - uid=1000
  - gid=1000
  - vers=3.0
  - nobrl
  - cache=strict