apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
  namespace: kube-system 
spec:
  interval: 5m
  chart:
    spec:
      chart: csi-driver-smb
      version: "1.9.0" # ¡VERIFICA LA ÚLTIMA VERSIÓN en el repositorio del chart!
      sourceRef:
        kind: HelmRepository
        name: smb-csi-driver
        namespace: flux-system
      interval: 1m
  install:
    remediation:
      remediateLastFailure: true
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
  values:
    smb:
      cloud: "" 
    controller:
      replicas: 1
    node:
      replicas: 1
    controllerServer:
      secretName: csi-smb-secret 
    nodeServer:
      secretName: csi-smb-secret
    csiDriver:
      kubeletRootDir: /var/lib/kubelet 
    volumeMounts:
      - mountPath: /mnt/smb
        name: smb-share
        hostPath: /mnt/smb 
    volumes:
      - name: smb-share
        hostPath:
          path: /mnt/smb
          type: DirectoryOrCreate