apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: smb-strict
provisioner: smb.csi.k8s.io
parameters:
  source: "//192.168.0.9/k8s-data"
  csi.storage.k8s.io/node-stage-secret-name: "csi-smb-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "kube-system"
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0700   
  - file_mode=0600  
  - uid=1001        
  - gid=1001        
  - vers=3.0
  - nobrl