apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n:latest
          env:
            - name: TZ
              value: "America/Mexico_City"
            - name: N8N_SECURE_COOKIE
              value: "false"
          ports:
            - name: http
              containerPort: 5678
          volumeMounts:
            - name: config
              mountPath: /home/node/.n8n
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: n8n-config