apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-config
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi