apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi