apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: "15.5.18"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    auth:
      existingSecret: "postgres-creds"
      database: "homelab"
    primary:
      # Este es el cambio clave para forzar el usuario correcto
      podSecurityContext:
        enabled: true
        fsGroup: 1001
      containerSecurityContext:
        enabled: true
        runAsUser: 1001
      persistence:
        enabled: true
        storageClass: "smb-strict"
        size: 8Gi
        subPath: "postgresql-data"