apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - transmission-config-pv.yaml
  - transmission-pvc.yaml
  - transmission-deployment.yaml
  - transmission-networking.yaml
  
