apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: media-stack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-dynamic  
  volumeName: transmission-config-pv  