# cluster/apps/media-stack/helm-release-qbittorrent.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media-stack
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: "1.5.1"
      sourceRef:
        kind: HelmRepository
        name: community-charts
        namespace: flux-system
  values:
    persistence:
      config:
        existingClaim: "qbittorrent-config"
      

    
    extraVolumes:
      - name: smb-downloads
        hostPath:
          path: /mnt/windows-media 

    extraVolumeMounts:
      - name: smb-downloads
        mountPath: /downloads 
    
    ingress:
      enabled: true
      hostname: "downloads.homelab.local"
      path: /
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: web