# cluster/apps/tailscale/tailscale-subnet-router.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subnet-router
  namespace: tailscale
  labels:
    app: subnet-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subnet-router
  template:
    metadata:
      labels:
        app: subnet-router
    spec:
      containers:
      - name: tailscale
        image: tailscale/tailscale:latest
        env:
        - name: TS_ROUTES
          value: "192.168.1.0/24"
        # Esta parte es segura. Simplemente le dice al deployment
        # que busque un secreto que ya existe en el clúster.
        - name: TS_AUTH_KEY
          valueFrom:
            secretKeyRef:
              name: tailscale-auth
              key: TS_AUTHKEY
        securityContext:
          capabilities:
            add:
              - NET_ADMIN