apiVersion: v1
kind: Namespace
metadata:
  name: networking
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: adguard-home
      version: "0.13.0"
      sourceRef:
        kind: OCIRepository
        name: adguard-gabe565 # Debe coincidir con el nombre de la fuente OCI
        namespace: flux-system
  values:
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 4Gi
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: adguard.homelab.local
          paths:
            - path: /
              pathType: Prefix