apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: commafeed
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/commafeed
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: database
    - name: media-stack 