apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homelab-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: homepage.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage
            port:
              number: 3000
  - host: pgadmin.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pgadmin-service
            port:
              number: 80
  - host: commafeed.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: commafeed-service
            port:
              number: 8082
  - host: readeck.homelab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: readeck
            port:
              number: 8000