apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Instalaciones base con dependencias
  #- ./metallb-install.yaml
  #- ./metallb-config.yaml
  #- ./traefik-install.yaml

  # Aplicaciones que dependen de las bases
  #- ./networking-adguard.yaml
  #- ./media.yaml
  #- ./database.yaml
  #- ./monitoring.yaml
  #- ./homepage.yaml
  #- ./tailscale.yaml

  # Aplicaciones que dependen de otras apps (como database)
  #- ./pgadmin.yaml
  #- ./commafeed.yaml
  #- ./media-stack.yaml
  #- ./n8n.yaml
 # - ./readeck.yaml
