apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
 - ./metallb-install.yaml
 - ./metallb-config.yaml
 - ./networking-adguard.yaml 
 - ./traefik-install.yaml
 #- ./traefik-system 
 #- ./networking/
 - ./media 
 - ./database 
 - ./media-stack
 - ./pgadmin
 - ./commafeed
 - ./homepage.yaml
 - ./monitoring.yaml 
