---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  # Este recurso de Kustomization aplica la configuración de MetalLB.
  name: metallb-config
  namespace: flux-system
spec:
  interval: 10m
  # Le dice a Flux que espere a que la Kustomization de instalación 'metallb-install' esté lista.
  dependsOn:
    - name: metallb-install
  
  # Apunta al repositorio principal de tu homelab.
  sourceRef:
    kind: GitRepository
    name: flux-system
  
  # Le decimos a Flux que no busque archivos en una ruta,
  # sino que aplique los recursos que definimos aquí mismo.
  path: "./" 
  prune: true
  
  # Estos son los manifiestos que se aplicarán.
  patches:
    - patch: |
        # --- Pool de IPs ---
        apiVersion: metallb.io/v1beta1
        kind: IPAddressPool
        metadata:
          name: primary-pool
          namespace: metallb-system
        spec:
          addresses:
            # IMPORTANTE: ¡Ajusta este rango a tu red local!
            - "192.168.1.54-192.168.1.64"
        ---
        # --- Anuncio en la red ---
        apiVersion: metallb.io/v1beta1
        kind: L2Advertisement
        metadata:
          name: default
          namespace: metallb-system
        spec:
          ipAddressPools:
            - primary-pool
      # Objetivo del parche: se aplica a este mismo recurso.
      target:
        group: kustomize.config.k8s.io
        version: v1beta1
        kind: Kustomization
        name: metallb-config