# cluster/apps/networking-adguard.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: networking-adguard
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cluster/apps/networking/adguard
  dependsOn:
    - name: traefik-install 