# cluster/apps/tailscale.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps/tailscale # <- Apunta a la carpeta de nuestra app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system