apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: media-stack:apps/Deployment:media-stack/qbittorrent
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: media-stack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      # INIT CONTAINER PARA FORZAR LA CONFIGURACIÓN CORRECTA
      initContainers:
      - name: fix-qbittorrent-config
        image: busybox:latest
        command: 
        - /bin/sh
        - -c
        - |
          echo "Creando estructura de directorios..."
          mkdir -p /media/downloads/incomplete
          mkdir -p /media/downloads/complete/movies
          mkdir -p /media/downloads/complete/tv
          mkdir -p /media/downloads/complete/music
          
          echo "Configurando qBittorrent..."
          mkdir -p /config/qBittorrent
          
          # Si ya existe configuración, la actualizamos
          if [ -f /config/qBittorrent/qBittorrent.conf ]; then
            echo "Actualizando configuración existente..."
            sed -i 's|Downloads\\SavePath=.*|Downloads\\SavePath=/media/downloads/incomplete/|g' /config/qBittorrent/qBittorrent.conf
            sed -i 's|Downloads\\TempPath=.*|Downloads\\TempPath=/media/downloads/incomplete/|g' /config/qBittorrent/qBittorrent.conf
          else
            echo "Creando nueva configuración..."
            cat > /config/qBittorrent/qBittorrent.conf << 'EOF'
          [BitTorrent]
          Session\AddTorrentStopped=false
          Session\DefaultSavePath=/media/downloads/incomplete

          [Preferences]
          Connection\PortRangeMin=6881
          Connection\UPnP=false
          Downloads\SavePath=/media/downloads/incomplete/
          Downloads\TempPath=/media/downloads/incomplete/
          General\Locale=en
          WebUI\Port=8080
          EOF
          fi
          
          echo "Configuración completada"
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /media
          name: downloads
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: America/Mexico_City
        - name: WEBUI_PORT
          value: "8080"
        image: lscr.io/linuxserver/qbittorrent:latest
        name: qbittorrent
        ports:
        - containerPort: 8080
          name: webui
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /media
          name: downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: qbittorrent-config
      - name: downloads
        persistentVolumeClaim:
          claimName: media-nfs-pvc