# cluster/apps/media-stack/qbittorrent-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media-stack
  labels:
    app: qbittorrent
spec:
  replicas: 1
  strategy:
   type: Recreate 
  selector: 
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
        - name: wait-for-smb
          image: busybox:1.36
          command: ['sh', '-c', 'until mountpoint -q /media; do echo "waiting for SMB mount..."; sleep 5; done']
          volumeMounts:
            - name: downloads
              mountPath: /media
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Mexico_City"
            - name: WEBUI_PORT
              value: "8080" 
          ports:
            - name: webui
              containerPort: 8080
            - name: torrent-tcp
              containerPort: 6881
            - name: torrent-udp
              containerPort: 6881
              protocol: UDP
          readinessProbe:
            httpGet:
              path: /login
              port: webui
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          hostPath:
            path: /mnt/windows-media 