apiVersion: v1
kind: ConfigMap
metadata:
  name: readeck-entrypoint
  namespace: readeck
data:
  entrypoint.sh: |

    export READECK_DATABASE_SOURCE="postgres://readeck:${POSTGRES_PASSWORD}@readeck-postgres-postgresql.readeck.svc.cluster.local:5432/readeck?sslmode=disable"
    
    echo "Starting Readeck with correctly configured database source..."
    
    /app/readeck