apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readeck-postgres-data
  namespace: readeck
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-readeck-db
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readeck-data
  namespace: readeck
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-dynamic
  resources:
    requests:
      storage: 10Gi