# cluster/apps/readeck/readeck-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readeck
  namespace: readeck
  labels:
    app: readeck
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: readeck
  template:
    metadata:
      labels:
        app: readeck
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        # Este contenedor no cambia, espera por el secreto
        - name: wait-for-secret
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              until kubectl get secret readeck-postgres-postgresql -n readeck >/dev/null 2>&1; do
                echo "Waiting for secret 'readeck-postgres-postgresql' to be created..."
                sleep 2
              done
              echo "Secret 'readeck-postgres-postgresql' found!"
        # ESTE ES EL CONTENEDOR MEJORADO
        - name: wait-for-db
          image: docker.io/bitnami/postgresql:16.3.0-debian-12-r21 # Usamos una imagen que tiene pg_isready
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: readeck-postgres-postgresql
                  key: postgres-password
          command:
            - /bin/sh
            - -c
            - |
              export PGPASSWORD="$POSTGRES_PASSWORD"
              until pg_isready -h readeck-postgres-postgresql.readeck.svc.cluster.local -U readeck -d readeck -p 5432; do
                echo "Waiting for PostgreSQL to be truly ready..."
                sleep 5
              done
              echo "PostgreSQL is ready to accept connections!"
      containers:
        - name: readeck
          image: codeberg.org/readeck/readeck:0.14.0
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: READECK_SERVER_HOST
              value: "0.0.0.0"
            - name: READECK_SERVER_PORT
              value: "8000"
            - name: READECK_DATABASE_DRIVER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: readeck-postgres-postgresql
                  key: postgres-password
            - name: READECK_DATABASE_SOURCE
              value: "postgres://readeck:$(POSTGRES_PASSWORD)@readeck-postgres-postgresql.readeck.svc.cluster.local:5432/readeck?sslmode=disable"
            - name: READECK_LOG_LEVEL
              value: "info"
            - name: TZ
              value: "America/Mexico_City"
          volumeMounts:
            - name: readeck-data
              mountPath: /readeck
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: readeck-data
          persistentVolumeClaim:
            claimName: readeck-data