# cluster/apps/readeck/readeck-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: readeck
  namespace: readeck
  labels:
    app: readeck
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: readeck
  template:
    metadata:
      labels:
        app: readeck
    spec:
      serviceAccountName: readeck
      containers:
        - name: readeck
          image: codeberg.org/readeck/readeck:0.14.0
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: READECK_SERVER_HOST
              value: "0.0.0.0"
            - name: READECK_SERVER_PORT
              value: "8000"
            - name: READECK_DATABASE_DRIVER
              value: "postgres"
            - name: READECK_DATABASE_SOURCE
              valueFrom:
                secretKeyRef:
                  name: readeck-secrets
                  key: database-url-helm 
            - name: READECK_LOG_LEVEL
              value: "info"
            - name: TZ
              value: "America/Mexico_City"
          volumeMounts:
            - name: readeck-data
              mountPath: /readeck
      volumes:
        - name: readeck-data
          persistentVolumeClaim:
            claimName: readeck-data