---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: readeck
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: readeck
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: readeck-chart
        namespace: flux-system
  values:
    # Usamos 'env' para inyectar directamente la variable que la app espera
    env:
      # El nombre de la variable que Readeck usa
      - name: READECK_DATABASE_URL
        # Obtenemos el valor completo desde el secreto que ya creamos
        valueFrom:
          secretKeyRef:
            name: readeck-db-secret
            key: READECK_DATABASE_URL

    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: "readeck.homelab.local"
          paths:
            - path: /
              pathType: Prefix
    
    persistence:
      enabled: true
      storageClass: "local-path"
      size: 5Gi
      accessMode: ReadWriteOnce