apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: glace-config
  namespace: glace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi