apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: database 
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "Homelab PostgreSQL",
          "Group": "Servers",
          "Host": "postgresql.database.svc.cluster.local",
          "Port": 5432,
          "MaintenanceDB": "homelab",
          "Username": "postgres",
          "SSLMode": "prefer"
        }
      }
    }