apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-dynamic
  resources:
    requests:
      storage: 2Gi