apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  
  resources:
    requests:
      storage: 2Gi 