# cluster/apps/pgadmin/pgadmin-pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # <--- ESTE ES EL CAMBIO CLAVE
  resources:
    requests:
      storage: 2Gi 