apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: weave-gitops
  namespace: weave-gitops
spec:
  interval: 15m
  chart:
    spec:
      chart: weave-gitops
      version: "4.0.36" 
      sourceRef:
        kind: HelmRepository
        name: weave-gitops
        namespace: flux-system
  values:
    adminUser:
      create: true
    flux:
      namespace: "flux-system"