apiVersion: v1
kind: Service
metadata:
  name: karakeep-chrome
  namespace: karakeep
  labels:
    app: karakeep-chrome
spec:
  selector:
    app: karakeep-chrome
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
  type: ClusterIP