apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-dynamic
  resources:
    requests:
      storage: 10Gi