apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-karakeep  
  resources:
    requests:
      storage: 5Gi