# cluster/apps/karakeep/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep-web
  namespace: karakeep
  labels:
    app: karakeep-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep-web
  template:
    metadata:
      labels:
        app: karakeep-web
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: karakeep-web
          image: ghcr.io/karakeep-app/karakeep:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /data
          envFrom:
            - secretRef:
                name: karakeep-secrets
            - configMapRef:
                name: karakeep-configuration
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: karakeep-data