# cluster/apps/karakeep/web-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep-web
  namespace: karakeep
  labels:
    app: karakeep-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep-web
  template:
    metadata:
      labels:
        app: karakeep-web
    spec:
      # This Init Container will run first and prepare the database
      initContainers:
        - name: db-migration
          image: ghcr.io/karakeep-app/karakeep:latest
          command: ["sh", "-c", "npx prisma migrate deploy"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: DATABASE_URL
          volumeMounts:
            - name: data
              mountPath: /app/data

      # This is your existing application container
      containers:
        - name: karakeep-web
          image: ghcr.io/karakeep-app/karakeep:latest
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: DATABASE_URL
            - name: MEILISEARCH_HOST
              value: "http://meilisearch.karakeep.svc.cluster.local:7700"
            - name: MEILISEARCH_KEY
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: MEILISEARCH_KEY
            - name: BROWSERLESS_HOST
              value: "http://karakeep-chrome.karakeep.svc.cluster.local:3001"
            - name: NEXTAUTH_URL
              value: "http://karakeep.homelab.local" 
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: NEXTAUTH_SECRET
            - name: AI_PROVIDER
              value: "gemini" 
            - name: GEMINI_API_KEY 
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: GEMINI_API_KEY 
            - name: TIMEZONE
              value: "America/Mexico_City"
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: karakeep-data