apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
  labels:
    app: wallabag
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          # 1. LA CLAVE: Usar la imagen de LinuxServer.io
          image: lscr.io/linuxserver/wallabag:latest
          ports:
            - containerPort: 80
          env:
            # 2. El script de esta imagen usar치 PUID/PGID para arreglar los permisos autom치ticamente.
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Mexico_City"
            # El resto de tus variables de entorno siguen igual.
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              value: "postgres"
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "http://wallabag.homelab.local"
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: postgres-password
            - name: SYMFONY__ENV__SECRET
              valueFrom:
                secretKeyRef:
                  name: wallabag-creds
                  key: SYMFONY_SECRET
          volumeMounts:
            # 3. Las im치genes de LinuxServer usan /config para los datos de la aplicaci칩n.
            - name: data
              mountPath: /config
            - name: images
              mountPath: /var/www/wallabag/web/assets/images
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1.5Gi"
              cpu: "1500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wallabag-data
        - name: images
          persistentVolumeClaim:
            claimName: wallabag-images