apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
  labels:
    app: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      # 1. El initContainer se ejecuta como root y prepara los volúmenes.
      initContainers:
        - name: set-permissions
          image: busybox:1.36
          # 2. No solo cambiamos el propietario, sino que forzamos los permisos de escritura.
          command:
            - "/bin/sh"
            - "-c"
            - |
              chown -R 1000:1000 /data /images
              chmod -R 775 /data /images
          volumeMounts:
            - name: data
              mountPath: /data
            - name: images
              mountPath: /images
      
      # 3. El contenedor principal se ejecuta de forma segura como usuario 1000.
      containers:
        - name: wallabag
          image: ghcr.io/wallabag/docker:2.6.10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          # 4. Usamos el comando de inicio correcto.
          command: ["/entrypoint.sh", "wallabag"]
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              value: "postgres"
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "http://wallabag.homelab.local"
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: postgres-password
            - name: SYMFONY__ENV__SECRET
              valueFrom:
                secretKeyRef:
                  name: wallabag-creds
                  key: SYMFONY_SECRET
          volumeMounts:
            - name: data
              mountPath: /var/www/wallabag/var
            - name: images
              mountPath: /var/www/wallabag/web/assets/images
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1.5Gi"
              cpu: "1500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wallabag-data
        - name: images
          persistentVolumeClaim:
            claimName: wallabag-images