apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
  labels:
    app: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: set-permissions
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 1000:1000 /data && chown -R 1000:1000 /images"]
          volumeMounts:
            - name: data
              mountPath: /data
            - name: images
              mountPath: /images
      containers:
        - name: wallabag
          image: ghcr.io/wallabag/docker:2.6.10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          # --- START: DEBUGGING CHANGE ---
          # Override the entrypoint to keep the container running
          command: ["/bin/sh", "-c"]
          args: ["sleep 3600"]
          # --- END: DEBUGGING CHANGE ---
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "postgresql.database.svc.cluster.local"
            # ... (rest of your env vars) ...
          volumeMounts:
            - name: data
              mountPath: /var/www/wallabag/var
            - name: images
              mountPath: /var/www/wallabag/web/assets/images
          # ... (rest of your deployment) ...
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wallabag-data
        - name: images
          persistentVolumeClaim:
            claimName: wallabag-images