apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
  labels:
    app: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      # Sin securityContext, para que el contenedor se ejecute como root, que es lo que necesita.
      containers:
        - name: wallabag
          image: ghcr.io/wallabag/docker:2.6.10
          # Este comando se ejecuta como root y hace dos cosas:
          # 1. 'chown': Arregla los permisos de los volúmenes para el usuario de la aplicación.
          # 2. 'exec': Inicia la aplicación de forma correcta para que no se detenga.
          command: ["/bin/sh", "-c"]
          args:
            - "chown -R 1000:1000 /var/www/wallabag/var /var/www/wallabag/web/assets/images && exec /entrypoint.sh wallabag"
          ports:
            - containerPort: 80
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "postgresql.database.svc.cluster.local"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              value: "postgres"
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "http://wallabag.homelab.local"
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-creds
                  key: postgres-password
            - name: SYMFONY__ENV__SECRET
              valueFrom:
                secretKeyRef:
                  name: wallabag-creds
                  key: SYMFONY_SECRET
          volumeMounts:
            - name: data
              mountPath: /var/www/wallabag/var
            - name: images
              mountPath: /var/www/wallabag/web/assets/images
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "1.5Gi"
              cpu: "1500m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wallabag-data
        - name: images
          persistentVolumeClaim:
            claimName: wallabag-images