apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-data
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-dynamic
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-images
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: smb-dynamic
  resources:
    requests:
      storage: 10Gi