# cluster/apps/metallb/depends-on.yaml
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  interval: 1m
  # Le dice a Flux que espere a que el HelmRelease 'metallb' esté listo
  dependsOn:
    - name: metallb
      namespace: metallb-system
  # Apunta al mismo repositorio y rama que tu sistema principal de Flux
  sourceRef:
    kind: GitRepository
    name: flux-system # O el nombre de tu GitRepository principal
  # Ruta a un archivo que no existe para que solo aplique el 'patch'
  path: "./"
  prune: false
  # Usa un patch para aplicar la configuración de la IP
  patches:
    - patch: |
        - op: add
          path: /spec/resources/-
          value:
            apiVersion: metallb.io/v1beta1
            kind: IPAddressPool
            metadata:
              name: primary-pool
              namespace: metallb-system
            spec:
              addresses:
                - "192.168.1.54-192.168.1.64" 
        - op: add
          path: /spec/resources/-
          value:
            apiVersion: metallb.io/v1beta1
            kind: L2Advertisement
            metadata:
              name: default
              namespace: metallb-system
            spec:
              ipAddressPools:
                - primary-pool
      target:
        group: kustomize.config.k8s.io
        version: v1beta1
        kind: Kustomization
        name: metallb-config