# cluster/apps/metallb/metallb-config.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: primary-pool
  namespace: metallb-system
spec:
  addresses:
    # ---------------------------------------------------------
    # IMPORTANTE: Cambia este rango de IPs a uno que esté
    # libre en tu red local (LAN).
    # Ejemplo: "192.168.1.240-192.168.1.250"
    # ---------------------------------------------------------
    - "192.168.1.54-192.168.1.64"
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - primary-pool