apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguard-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-dynamic
  nfs:
    server: 192.168.0.21
    path: "/mnt/tokyo-3/k8s-data/adguard/data"