apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: networking
  labels:
    app: adguard-home
spec:
  replicas: 1
  strategy:
    type: Recreate  # Porque usamos PVC ReadWriteOnce
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:v0.107.52
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        volumeMounts:
        - name: adguard-config
          mountPath: /opt/adguardhome/conf
        - name: adguard-data
          mountPath: /opt/adguardhome/work
        env:
        - name: TZ
          value: "America/Mexico_City"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: adguard-config
        persistentVolumeClaim:
          claimName: adguard-config
      - name: adguard-data
        persistentVolumeClaim:
          claimName: adguard-data