# cluster/apps/networking/adguard/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: networking
  labels:
    app: adguard-home
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      containers:
      - name: adguard-home
        image: adguard/adguardhome:v0.107.52
        ports:
        - containerPort: 80
          name: http
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        volumeMounts:
        - name: adguard-config
          mountPath: /opt/adguardhome/conf
          subPath: adguard/config
        - name: adguard-data
          mountPath: /opt/adguardhome/work
          subPath: adguard/data
        env:
        - name: TZ
          value: "America/Mexico_City"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # --- MODIFIED PROBES ---
        livenessProbe:
          httpGet:
            path: /control/status
            port: 80
          initialDelaySeconds: 60 # Increased from 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /control/status
            port: 80
          initialDelaySeconds: 30 # Increased from 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
        # --- END OF MODIFICATIONS ---
      volumes:
      - name: adguard-config
        persistentVolumeClaim:
          claimName: adguard-config
      - name: adguard-data
        persistentVolumeClaim:
          claimName: adguard-data