apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-config
  namespace: networking
  labels:
    app: adguard-home
    component: config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi