apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  namespace: networking
  labels:
    app: adguard-home
    component: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-dynamic
  resources:
    requests:
      storage: 2Gi
  volumeName: adguard-data-pv        

