apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  namespace: networking
  labels:
    app: adguard-home
spec:
  selector:
    app: adguard-home
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
  type: ClusterIP