---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: readeck-chart
  namespace: flux-system
spec:
  interval: 1h
  # ESTA ES LA URL CORRECTA PARA EL HELM CHART
  url: https://zekker6.github.io/readeck-helm-chart