# cluster/apps/media-stack/prowlarr/prowlarr-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-stack
  labels:
    app: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
        - name: wait-for-smb
          image: busybox:1.36
          command: ['sh', '-c', 'until [ -d "/media" ] && [ "$(ls -A /media)" ]; do echo "waiting for SMB mount to be populated..."; sleep 5; done']          command: ['sh', '-c', 'until [ -d "/media/movies" ] && [ -d "/media/tv" ]; do echo "waiting for SMB subfolders..."; sleep 5; done']
          volumeMounts:
            - name: downloads
              mountPath: /media
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Mexico_City"
          ports:
            - name: http
              containerPort: 9696
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads 
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: downloads 
          hostPath:
            path: /mnt/windows-media