# cluster/apps/media-stack/prowlarr/prowlarr-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-stack
  labels:
    app: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      initContainers:
       - name: wait-for-nfs
         image: busybox:1.36
         command: ['sh', '-c', 'until mountpoint -q /media; do echo "waiting for NFS mount..."; sleep 5; done; echo "NFS mount ready"']
         volumeMounts:
         - name: downloads
           mountPath: /media
      containers:
        - name: prowlarr
          image: lscr.io/linuxserver/prowlarr:latest
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Mexico_City"
          ports:
            - name: http
              containerPort: 9696
          readinessProbe:
            httpGet:
              path: /login
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: prowlarr
            - name: downloads 
              mountPath: /media
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: prowlarr-config
        - name: downloads 
          persistentVolumeClaim:
            claimName: media-nfs-pvc