# cluster/apps/external-services/jellyfin.yaml
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: external-services
spec:
  ports:
  - protocol: TCP
    port: 8096
    targetPort: 8096
---
apiVersion: v1
kind: Endpoints
metadata:
  name: jellyfin
  namespace: external-services
subsets:
  - addresses:
      - ip: "192.168.0.220"
    ports:
      - port: 8096
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyfin
  namespace: external-services
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`jelly.homelab.local`)
    kind: Rule
    services:
    - name: jellyfin
      port: 8096