# cluster/apps/external-services/plex.yaml
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: external-services
spec:
  ports:
  - protocol: TCP
    port: 32400
    targetPort: 32400
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex
  namespace: external-services
subsets:
  - addresses:
      - ip: "192.168.0.221"
    ports:
      - port: 32400
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex
  namespace: external-services
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`plex.homelab.local`)
    kind: Rule
    services:
    - name: plex
      port: 32400