# cluster/apps/external-services/proxmox.yaml
apiVersion: v1
kind: Service
metadata:
  name: proxmox
  namespace: external-services
spec:
  ports:
  - protocol: TCP
    port: 8006
    targetPort: 8006
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox
  namespace: external-services
subsets:
  - addresses:
      - ip: "192.168.0.10"
    ports:
      - port: 8006
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: proxmox-transport
  namespace: external-services
spec:
  insecureSkipVerify: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: external-services
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`proxmox.homelab.local`)
    kind: Rule
    services:
    - name: proxmox
      port: 8006
      scheme: https 
      serversTransport: proxmox-transport