# foalaniz/homelab-k3s/cluster/apps/metallb/config/ip-pool.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: static-pool
  namespace: metallb-system
spec:
  addresses:
    - "192.168.1.45-192.168.1.46" 
  autoAssign: false 
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dynamic-pool
  namespace: metallb-system
spec:
  addresses:
    - "192.168.1.50-192.168.1.64" 
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - static-pool
    - dynamic-pool